# Matrix Manipulations


**Matrices** are the R objects in which the elements are arranged in a two-dimensional rectangular layout. They contain elements of the same atomic types. Though we can create a matrix containing only characters or only logical values, they are not of much use. We use matrices containing numeric elements to be used in mathematical calculations.

A Matrix is created using the matrix() function.

In [1]:
# create a 3x3 matrix
matrix_3x3 <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3)

# print the matrix
print(matrix_3x3)


     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [2]:
# transpose the 3x3 matrix
matrix_3x3_transposed <- t(matrix_3x3)

# print the transposed matrix
print(matrix_3x3_transposed)


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [4]:
# extract the submatrix consisting of the first 2 rows and 2 columns of the 3x3 matrix
submatrix <- matrix_3x3[1:2, 1:2]

# print the submatrix
print(submatrix)


     [,1] [,2]
[1,]    1    4
[2,]    2    5


In [5]:
# add a new row to the 3x3 matrix
new_row <- c(10, 11, 12)
matrix_3x3_with_row <- rbind(matrix_3x3, new_row)

# add a new column to the 3x3 matrix
new_column <- c(10, 11, 12)
matrix_3x3_with_column <- cbind(matrix_3x3, new_column)

# print the matrices with the new row and column
print(matrix_3x3_with_row)
print(matrix_3x3_with_column)


        [,1] [,2] [,3]
           1    4    7
           2    5    8
           3    6    9
new_row   10   11   12
           new_column
[1,] 1 4 7         10
[2,] 2 5 8         11
[3,] 3 6 9         12


In [6]:
# calculate the determinant of the 2x2 matrix
matrix_det <- det(matrix_2x2)

# print the determinant
print(matrix_det)


[1] -2


In [7]:
# invert the 2x2 matrix
matrix_inverse <- solve(matrix_2x2)

# print the inverted matrix
print(matrix_inverse)


     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5


In [8]:
# calculate the trace of the 3x3 matrix
matrix_trace <- sum(diag(matrix_3x3))

# print the trace
print(matrix_trace)


[1] 15


In [9]:
# create a function that doubles its input
double_function <- function(x) {
  return(x * 2)
}

# apply the function to each element of the 3x3 matrix
matrix_doubled <- apply(matrix_3x3, c(1, 2), double_function)

# print the doubled matrix
print(matrix_doubled)


     [,1] [,2] [,3]
[1,]    2    8   14
[2,]    4   10   16
[3,]    6   12   18


In [10]:
# create a 2x4 matrix
matrix_2x4 <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2)

# reshape the 2x4 matrix into a 4x2 matrix
matrix_4x2 <- t(matrix_2x4)

# print the reshaped matrix
print(matrix_4x2)


     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8


In [11]:
# create a 2x3 matrix
matrix_2x3a <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2)

# create a second 2x3 matrix
matrix_2x3b <- matrix(c(7, 8, 9, 10, 11, 12), nrow = 2)

# concatenate the two matrices vertically
matrix_4x3 <- rbind(matrix_2x3a, matrix_2x3b)

# print the concatenated matrix
print(matrix_4x3)


     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[3,]    7    9   11
[4,]    8   10   12


In [12]:
# create a 2x3 matrix
matrix_2x3 <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2)

# scale the matrix by a factor of 2
matrix_scaled <- matrix_2x3 * 2

# print the scaled matrix
print(matrix_scaled)


     [,1] [,2] [,3]
[1,]    2    6   10
[2,]    4    8   12


In [13]:
# create a 2x3 matrix
matrix_2x3 <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2)

# add 1 to each element of the matrix
matrix_added <- matrix_2x3 + 1

# print the modified matrix
print(matrix_added)


     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    3    5    7


In [17]:
# create a 3x3 matrix
matrix_3x3 <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3)

# calculate the eigenvalues and eigenvectors of the matrix
eigen_results <- eigen(matrix_3x3)

# print the eigenvalues and eigenvectors
print(eigen_results$values)
print(eigen_results$vectors)


[1]  1.611684e+01 -1.116844e+00 -5.700691e-16
           [,1]       [,2]       [,3]
[1,] -0.4645473 -0.8829060  0.4082483
[2,] -0.5707955 -0.2395204 -0.8164966
[3,] -0.6770438  0.4038651  0.4082483


In [18]:
# load the Matrix package
library(Matrix)

# create a 3x3 matrix
matrix_3x3 <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3)

# convert the matrix to a sparse matrix
sparse_matrix <- Matrix(matrix_3x3, sparse = TRUE)

# find the rank of the matrix
rank <- rankMatrix(sparse_matrix)

# print the rank
print(rank)


[1] 2
attr(,"method")
[1] "tolNorm2"
attr(,"useGrad")
[1] FALSE
attr(,"tol")
[1] 6.661338e-16
